// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5oCyNbqmYbHDpLKrWijj8HXiOIUPm7TY',
    appId: '1:104158337491:web:9f845e948623bf73f8b726',
    messagingSenderId: '104158337491',
    projectId: 'my-cineroom-project-id',
    authDomain: 'my-cineroom-project-id.firebaseapp.com',
    storageBucket: 'my-cineroom-project-id.firebasestorage.app',
    measurementId: 'G-GWZH5Z8P01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxKy7KiFXKgoHUdI-6N-kF7EQYd33AfsM',
    appId: '1:104158337491:android:707139ff8c139a84f8b726',
    messagingSenderId: '104158337491',
    projectId: 'my-cineroom-project-id',
    storageBucket: 'my-cineroom-project-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARO-TKVFC--PALhu5RNrSG-aWNFtuo-Ak',
    appId: '1:104158337491:ios:6e62d3787816bc3ff8b726',
    messagingSenderId: '104158337491',
    projectId: 'my-cineroom-project-id',
    storageBucket: 'my-cineroom-project-id.firebasestorage.app',
    iosBundleId: 'com.example.newdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARO-TKVFC--PALhu5RNrSG-aWNFtuo-Ak',
    appId: '1:104158337491:ios:6e62d3787816bc3ff8b726',
    messagingSenderId: '104158337491',
    projectId: 'my-cineroom-project-id',
    storageBucket: 'my-cineroom-project-id.firebasestorage.app',
    iosBundleId: 'com.example.newdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5oCyNbqmYbHDpLKrWijj8HXiOIUPm7TY',
    appId: '1:104158337491:web:da2fe7928f9c6518f8b726',
    messagingSenderId: '104158337491',
    projectId: 'my-cineroom-project-id',
    authDomain: 'my-cineroom-project-id.firebaseapp.com',
    storageBucket: 'my-cineroom-project-id.firebasestorage.app',
    measurementId: 'G-G2631XJ2HL',
  );
}
